"""add_subsection_and_unique_constraint

Revision ID: ed3be8508cb7
Revises: 
Create Date: 2026-07-02 11:44:27.570414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3be8508cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_worker_equip_datetime', ['worker_id', 'equipment_id', 'log_date', 'log_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_worker_equip_datetime', type_='unique')

    # ### end Alembic commands ###
